import { createClient } from "@supabase/supabase-js";
import { cleanText, cleanName, safeLimit, requireUserId, isSameUser } from "./appSecurity";

const url=import.meta.env.VITE_SUPABASE_URL||"https://kpfezbmtmxczpdvqogje.supabase.co";
const key=import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY||import.meta.env.VITE_SUPABASE_ANON_KEY;
if(!url||!key) throw new Error("Configuração do Supabase ausente.");
export const supabase=createClient(url,key,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true},global:{headers:{"x-codex-client":"codex-vitae"}}});

const cleanEmail=v=>String(v||"").trim().toLowerCase();
export async function signUp(email,password,name){const cleanEmailValue=cleanEmail(email),cleanNameValue=cleanName(name);if(!cleanEmailValue)throw new Error("Digite seu e-mail.");if(!password||password.length<6)throw new Error("A senha precisa ter pelo menos 6 caracteres.");if(cleanNameValue.length<2)throw new Error("O nome precisa ter pelo menos 2 caracteres.");const {data,error}=await supabase.auth.signUp({email:cleanEmailValue,password,options:{data:{name:cleanNameValue}}});if(error)throw error;return{...data,email:cleanEmailValue,requiresEmailConfirmation:!data.session}}
export async function verifySignupCode(email,token){const {data,error}=await supabase.auth.verifyOtp({email:cleanEmail(email),token:String(token||"").replace(/\D/g,"").slice(0,6),type:"signup"});if(error)throw error;return data}
export async function resendConfirmation(email){const {error}=await supabase.auth.resend({type:"signup",email:cleanEmail(email)});if(error)throw error}
export async function signIn(email,password){const {data,error}=await supabase.auth.signInWithPassword({email:cleanEmail(email),password});if(error)throw error;return data}
export async function signOut(){const {error}=await supabase.auth.signOut();if(error)throw error}
export async function deleteMyAccount(){const {error}=await supabase.rpc("delete_my_account");if(error)throw error;await supabase.auth.signOut()}
export async function getProfile(userId){requireUserId(userId);const {data,error}=await supabase.from("profiles").select("*").eq("id",userId).maybeSingle();if(error)throw error;if(!data)throw new Error("Perfil não encontrado.");return data}
export async function saveProfile(profile){const safe={...profile,id:requireUserId(profile?.id),name:cleanName(profile?.name)};delete safe.email;delete safe.role;delete safe.is_admin;const {data,error}=await supabase.from("profiles").upsert(safe,{onConflict:"id"}).select();if(error)throw error;if(!data?.length)throw new Error("Não foi possível salvar o perfil.");return data[0]}
export async function updateProgress(userId,patch){requireUserId(userId);const allowed={};for(const k of ["level","total_xp","quests_completed_ever","max_streak_ever","usage_seconds"]){if(Object.prototype.hasOwnProperty.call(patch||{},k))allowed[k]=Math.max(0,Number(patch[k])||0)}const {error}=await supabase.from("profiles").update(allowed).eq("id",userId);if(error)throw error;return getProfile(userId)}
export async function claimSystemMission(missionDate,difficulty,xp){const {data,error}=await supabase.rpc("claim_system_mission",{p_mission_date:missionDate,p_difficulty:difficulty,p_xp:Math.max(0,Number(xp)||0)});if(error)throw error;return data}
const profileFields="id,name,avatar_url,level,total_xp,quests_completed_ever,max_streak_ever,usage_seconds,equipped_title,is_private";
export async function getFeed(limit=200){const {data,error}=await supabase.from("posts").select(`*, profiles!posts_author_id_fkey(${profileFields})`).order("created_at",{ascending:false}).limit(safeLimit(limit,200));if(error)throw error;return data||[]}
export async function getFriendIds(userId){requireUserId(userId);const {data,error}=await supabase.from("friend_requests").select("sender_id,receiver_id").eq("status","accepted").or(`sender_id.eq.${userId},receiver_id.eq.${userId}`);if(error)throw error;return [...new Set((data||[]).map(r=>r.sender_id===userId?r.receiver_id:r.sender_id))]}
export async function getFriendsFeed(userId,limit=200){const ids=await getFriendIds(userId);if(!ids.length)return[];const {data,error}=await supabase.from("posts").select(`*, profiles!posts_author_id_fkey(${profileFields})`).in("author_id",ids).order("created_at",{ascending:false}).limit(safeLimit(limit,200));if(error)throw error;return data||[]}
export async function publishPost({authorId,text,imageUrl=null,achievementId=null}){requireUserId(authorId);const clean=cleanText(text);if(!clean&&!imageUrl)throw new Error("Escreva algo ou escolha uma foto para publicar.");const {data,error}=await supabase.from("posts").insert({author_id:authorId,text:clean,image_url:imageUrl,achievement_id:achievementId}).select(`*, profiles!posts_author_id_fkey(${profileFields})`).single();if(error)throw error;return data}
export async function updatePost(postId,authorId,text){requireUserId(authorId);const clean=cleanText(text);if(!postId||!clean)throw new Error("A publicação não pode ficar vazia.");const {data,error}=await supabase.from("posts").update({text:clean}).eq("id",postId).eq("author_id",authorId).select(`*, profiles!posts_author_id_fkey(${profileFields})`).single();if(error)throw error;return data}
export async function deletePost(postId,authorId){requireUserId(authorId);const {error}=await supabase.from("posts").delete().eq("id",postId).eq("author_id",authorId);if(error)throw error}
export async function getComments(postId){const {data,error}=await supabase.from("comments").select(`*, profiles!comments_author_id_fkey(${profileFields})`).eq("post_id",postId).order("created_at",{ascending:true});if(error)throw error;return data||[]}
export async function addComment({postId,authorId,text}){requireUserId(authorId);const clean=cleanText(text);if(!postId||!clean)throw new Error("O comentário não pode ficar vazio.");const {data,error}=await supabase.from("comments").insert({post_id:postId,author_id:authorId,text:clean}).select(`*, profiles!comments_author_id_fkey(${profileFields})`).single();if(error)throw error;return data}
export function subscribeToComments(postId,onChange){return supabase.channel(`codex-comments-${postId}`).on("postgres_changes",{event:"*",schema:"public",table:"comments",filter:`post_id=eq.${postId}`},onChange).subscribe()}
export async function getMyLikes(userId){requireUserId(userId);const {data,error}=await supabase.from("likes").select("post_id").eq("user_id",userId);if(error)throw error;return new Set((data||[]).map(x=>x.post_id))}
export async function toggleLike(postId,userId,liked){requireUserId(userId);if(liked){const {error}=await supabase.from("likes").delete().eq("post_id",postId).eq("user_id",userId);if(error)throw error}else{const {error}=await supabase.from("likes").insert({post_id:postId,user_id:userId});if(error)throw error}const {count,error}=await supabase.from("likes").select("post_id",{count:"exact",head:true}).eq("post_id",postId);if(error)throw error;return{likes_count:count||0}}
export function subscribeToFeed(onChange){return supabase.channel(`codex-feed-${Math.random().toString(36).slice(2)}`).on("postgres_changes",{event:"*",schema:"public",table:"posts"},onChange).on("postgres_changes",{event:"*",schema:"public",table:"likes"},onChange).on("postgres_changes",{event:"*",schema:"public",table:"comments"},onChange).on("postgres_changes",{event:"*",schema:"public",table:"profiles"},onChange).on("postgres_changes",{event:"*",schema:"public",table:"friend_requests"},onChange).on("postgres_changes",{event:"*",schema:"public",table:"user_follows"},onChange).subscribe()}
export async function getLeaderboard(mode="level",limit=5000){const {data,error}=await supabase.rpc("get_global_leaderboard",{p_mode:mode,p_limit:safeLimit(limit,5000)});if(error)throw error;return data||[]}
export async function createPrivateConversation(myId,otherId){requireUserId(myId);if(isSameUser(myId,otherId))throw new Error("Você não pode conversar consigo mesmo.");const {data,error}=await supabase.rpc("create_private_conversation",{p_other_user_id:otherId});if(error)throw error;return data}
export async function getMyConversations(userId){requireUserId(userId);const {data:memberships,error}=await supabase.from("conversation_members").select("conversation_id").eq("user_id",userId);if(error)throw error;const ids=[...new Set((memberships||[]).map(x=>x.conversation_id))];if(!ids.length)return[];const {data:members,error:memberError}=await supabase.from("conversation_members").select(`conversation_id,user_id,profiles!conversation_members_user_id_fkey(${profileFields})`).in("conversation_id",ids);if(memberError)throw memberError;return ids.map(id=>({id,members:(members||[]).filter(m=>m.conversation_id===id).map(m=>m.profiles).filter(Boolean)}))}
export async function getMessages(conversationId){const {data,error}=await supabase.from("messages").select("*").eq("conversation_id",conversationId).order("created_at",{ascending:true});if(error)throw error;return data||[]}
export async function sendMessage(conversationId,senderId,text){requireUserId(senderId);const clean=cleanText(text);if(!conversationId||!clean)throw new Error("Digite uma mensagem.");const {data,error}=await supabase.from("messages").insert({conversation_id:conversationId,sender_id:senderId,text:clean}).select().single();if(error)throw error;return data}
export function subscribeToMessages(conversationId,onMessage){return supabase.channel(`codex-chat-${conversationId}`).on("postgres_changes",{event:"INSERT",schema:"public",table:"messages",filter:`conversation_id=eq.${conversationId}`},payload=>onMessage(payload.new)).subscribe()}
export async function followUser(followerId,followingId){requireUserId(followerId);if(isSameUser(followerId,followingId))throw new Error("Não é possível seguir este usuário.");const {error}=await supabase.from("user_follows").insert({follower_id:followerId,following_id:followingId});if(error&&error.code!=="23505")throw error}
export async function unfollowUser(followerId,followingId){requireUserId(followerId);const {error}=await supabase.from("user_follows").delete().eq("follower_id",followerId).eq("following_id",followingId);if(error)throw error}
export async function isFollowing(followerId,followingId){requireUserId(followerId);const {data,error}=await supabase.from("user_follows").select("id").eq("follower_id",followerId).eq("following_id",followingId).maybeSingle();if(error)throw error;return !!data}
export async function getFollowStats(userId){requireUserId(userId);const [{count:followers,error:e1},{count:following,error:e2}]=await Promise.all([supabase.from("user_follows").select("id",{count:"exact",head:true}).eq("following_id",userId),supabase.from("user_follows").select("id",{count:"exact",head:true}).eq("follower_id",userId)]);if(e1)throw e1;if(e2)throw e2;return{followers:followers||0,following:following||0}}
export async function getFollowers(userId){requireUserId(userId);const {data,error}=await supabase.from("user_follows").select(`follower_id,profiles!user_follows_follower_id_fkey(${profileFields})`).eq("following_id",userId).order("created_at",{ascending:false});if(error)throw error;return(data||[]).map(x=>x.profiles).filter(Boolean)}
export async function getFollowing(userId){requireUserId(userId);const {data,error}=await supabase.from("user_follows").select(`following_id,profiles!user_follows_following_id_fkey(${profileFields})`).eq("follower_id",userId).order("created_at",{ascending:false});if(error)throw error;return(data||[]).map(x=>x.profiles).filter(Boolean)}
export async function getFriendRequestStatus(me,other){requireUserId(me);const {data,error}=await supabase.from("friend_requests").select("id,sender_id,receiver_id,status").or(`and(sender_id.eq.${me},receiver_id.eq.${other}),and(sender_id.eq.${other},receiver_id.eq.${me})`).order("created_at",{ascending:false}).limit(1).maybeSingle();if(error)throw error;return data||null}
export async function sendFriendRequest(senderId,receiverId){requireUserId(senderId);if(isSameUser(senderId,receiverId))throw new Error("Você não pode adicionar a si mesmo.");const {data,error}=await supabase.from("friend_requests").insert({sender_id:senderId,receiver_id:receiverId,status:"pending"}).select().single();if(error&&error.code==="23505"){const existing=await getFriendRequestStatus(senderId,receiverId);if(existing?.status==="rejected"){const {data:updated,error:updateError}=await supabase.from("friend_requests").update({status:"pending",updated_at:new Date().toISOString()}).eq("id",existing.id).select().single();if(updateError)throw updateError;return updated}throw new Error("Pedido de amizade já enviado.")}if(error)throw error;return data}
export async function respondFriendRequest(requestId,accept){if(!requestId)throw new Error("Pedido inválido.");const {data,error}=await supabase.from("friend_requests").update({status:accept?"accepted":"rejected",updated_at:new Date().toISOString()}).eq("id",requestId).select().single();if(error)throw error;return data}
export async function getPendingFriendRequests(userId){requireUserId(userId);const {data,error}=await supabase.from("friend_requests").select(`id,sender_id,receiver_id,status,created_at,profiles!friend_requests_sender_id_fkey(${profileFields})`).eq("receiver_id",userId).eq("status","pending").order("created_at",{ascending:false});if(error)throw error;return data||[]}
export async function getAcceptedFriendIds(userId){return getFriendIds(userId)}