import { createClient } from "@supabase/supabase-js";
const url=import.meta.env.VITE_SUPABASE_URL||"https://kpfezbmtmxczpdvqogje.supabase.co";
const key=import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY||import.meta.env.VITE_SUPABASE_ANON_KEY||"sb_publishable_oD41poIileZVeuzUV7qspg_eIOE89tW";
export const supabase=createClient(url,key,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});
export async function signUp(email,password,name){const cleanEmail=String(email||"").trim().toLowerCase(),cleanName=String(name||"Aventureiro").trim()||"Aventureiro";if(!cleanEmail)throw new Error("Digite seu e-mail.");if(!password||password.length<6)throw new Error("A senha precisa ter pelo menos 6 caracteres.");if(cleanName.length<2)throw new Error("O nome precisa ter pelo menos 2 caracteres.");const {data,error}=await supabase.auth.signUp({email:cleanEmail,password,options:{data:{name:cleanName}}});if(error)throw error;return{...data,email:cleanEmail,requiresEmailConfirmation:!data.session}}
export async function signIn(email,password){const {data,error}=await supabase.auth.signInWithPassword({email:String(email||"").trim().toLowerCase(),password});if(error)throw error;return data}
export async function signOut(){const {error}=await supabase.auth.signOut();if(error)throw error}
export async function deleteMyAccount(){const {error}=await supabase.rpc("delete_my_account");if(error)throw error;await supabase.auth.signOut()}
export async function getProfile(userId){const {data,error}=await supabase.from("profiles").select("*").eq("id",userId).maybeSingle();if(error)throw error;if(!data)throw new Error("Perfil não encontrado.");return data}
export async function saveProfile(profile){const {data,error}=await supabase.from("profiles").upsert(profile,{onConflict:"id"}).select();if(error)throw error;if(!data?.length)throw new Error("Não foi possível salvar o perfil.");return data[0]}
export async function updateProgress(userId,patch){const {error}=await supabase.from("profiles").update(patch).eq("id",userId);if(error)throw error;return await getProfile(userId)}
export async function claimSystemMission(missionDate,difficulty,xp){const {data,error}=await supabase.rpc("claim_system_mission",{p_mission_date:missionDate,p_difficulty:difficulty,p_xp:xp});if(error)throw error;return data}
const profileFields="id,name,avatar_url,level,total_xp,quests_completed_ever,max_streak_ever,usage_seconds,equipped_title,is_private";
export async function getFeed(limit=200){const {data,error}=await supabase.from("posts").select(`*, profiles!posts_author_id_fkey(${profileFields})`).order("created_at",{ascending:false}).limit(Math.min(Math.max(limit,1),500));if(error)throw error;return data||[]}
export async function getFriendIds(userId){const {data,error}=await supabase.from("friend_requests").select("sender_id,receiver_id").eq("status","accepted").or(`sender_id.eq.${userId},receiver_id.eq.${userId}`);if(error)throw error;return [...new Set((data||[]).map(r=>r.sender_id===userId?r.receiver_id:r.sender_id))]}
export async function getFriendsFeed(userId,limit=200){const ids=await getFriendIds(userId);if(!ids.length)return[];const {data,error}=await supabase.from("posts").select(`*, profiles!posts_author_id_fkey(${profileFields})`).in("author_id",ids).order("created_at",{ascending:false}).limit(Math.min(Math.max(limit,1),500));if(error)throw error;return data||[]}
export async function publishPost({authorId,text,imageUrl=null,achievementId=null}){const cleanText=String(text||"").trim();if(!cleanText&&!imageUrl)throw new Error("Escreva algo ou escolha uma foto para publicar.");const {data,error}=await supabase.from("posts").insert({author_id:authorId,text:cleanText,image_url:imageUrl,achievement_id:achievementId}).select(`*, profiles!posts_author_id_fkey(${profileFields})`).single();if(error)throw error;return data}
export async function updatePost(postId,authorId,text){const clean=String(text||"").trim();if(!clean)throw new Error("A publicação não pode ficar vazia.");const {data,error}=await supabase.from("posts").update({text:clean}).eq("id",postId).eq("author_id",authorId).select(`*, profiles!posts_author_id_fkey(${profileFields})`).single();if(error)throw error;return data}
export async function deletePost(postId,authorId){const {error}=await supabase.from("posts").delete().eq("id",postId).eq("author_id",authorId);if(error)throw error}
export async function getComments(postId){const {data,error}=await supabase.from("comments").select(`*, profiles!comments_author_id_fkey(${profileFields})`).eq("post_id",postId).order("created_at",{ascending:true});if(error)throw error;return data||[]}
export async function addComment({postId,authorId,text}){const clean=String(text||"").trim();if(!clean)throw new Error("O comentário não pode ficar vazio.");const {data,error}=await supabase.from("comments").insert({post_id:postId,author_id:authorId,text:clean}).select(`*, profiles!comments_author_id_fkey(${profileFields})`).single();if(error)throw error;return data}
export function subscribeToComments(postId,onChange){return supabase.channel(`codex-comments-${postId}`).on("postgres_changes",{event:"*",schema:"public",table:"comments",filter:`post_id=eq.${postId}`},onChange).subscribe()}
export async function getMyLikes(userId){const {data,error}=await supabase.from("likes").select("post_id").eq("user_id",userId);if(error)throw error;return new Set((data||[]).map(x=>x.post_id))}
export async function toggleLike(postId,userId,liked){if(liked){const {error}=await supabase.from("likes").delete().eq("post_id",postId).eq("user_id",userId);if(error)throw error}else{const {error}=await supabase.from("likes").insert({post_id:postId,user_id:userId});if(error)throw error}const {count,error}=await supabase.from("likes").select("post_id",{count:"exact",head:true}).eq("post_id",postId);if(error)throw error;return{likes_count:count||0}}
export function subscribeToFeed(onChange){return supabase.channel(`codex-feed-global-${Math.random().toString(36).slice(2)}`).on("postgres_changes",{event:"*",schema:"public",table:"posts"},onChange).on("postgres_changes",{event:"*",schema:"public",table:"likes"},onChange).on("postgres_changes",{event:"*",schema:"public",table:"comments"},onChange).on("postgres_changes",{event:"*",schema:"public",table:"profiles"},onChange).on("postgres_changes",{event:"*",schema:"public",table:"friend_requests"},onChange).subscribe()}
export async function getLeaderboard(mode="level",limit=5000){const {data,error}=await supabase.rpc("get_global_leaderboard",{p_mode:mode,p_limit:Math.min(Math.max(limit,1),5000)});if(error)throw error;return data||[]}
export async function createPrivateConversation(myId,otherId){if(myId===otherId)throw new Error("Você não pode conversar consigo mesmo.");const {data,error}=await supabase.rpc("create_private_conversation",{p_other_user_id:otherId});if(error)throw error;return data}
export async function getMyConversations(userId){const {data:memberships,error}=await supabase.from("conversation_members").select("conversation_id").eq("user_id",userId);if(error)throw error;const ids=[...new Set((memberships||[]).map(x=>x.conversation_id))];if(!ids.length)return[];const {data:members,error:memberError}=await supabase.from("conversation_members").select(`conversation_id,user_id,profiles!conversation_members_user_id_fkey(${profileFields})`).in("conversation_id",ids);if(memberError)throw memberError;return ids.map(id=>({id,members:(members||[]).filter(m=>m.conversation_id===id).map(m=>m.profiles).filter(Boolean)}))}
export async function getMessages(conversationId){const {data,error}=await supabase.from("messages").select("*").eq("conversation_id",conversationId).order("created_at",{ascending:true});if(error)throw error;return data||[]}
export async function sendMessage(conversationId,senderId,text){const {data,error}=await supabase.from("messages").insert({conversation_id:conversationId,sender_id:senderId,text:text.trim()}).select().single();if(error)throw error;return data}
export function subscribeToMessages(conversationId,onMessage){return supabase.channel(`codex-chat-${conversationId}`).on("postgres_changes",{event:"INSERT",schema:"public",table:"messages",filter:`conversation_id=eq.${conversationId}`},payload=>onMessage(payload.new)).subscribe()}
