import React,{useEffect,useState}from'react';
import{MessageCircle,Users,UserPlus,UserCheck,UserMinus,Search,Send,X,Globe2,Heart,RefreshCw}from'lucide-react';
import{supabase,getFeed,getFriendsFeed,followUser,unfollowUser,isFollowing,getFollowStats,getFollowers,getFollowing,getFriendRequestStatus,sendFriendRequest,respondFriendRequest,getPendingFriendRequests,createPrivateConversation,getMyConversations,getMessages,sendMessage,subscribeToMessages}from'./lib/supabaseClient';

export default function SocialHub(){
 const[session,setSession]=useState(null),[open,setOpen]=useState(false),[tab,setTab]=useState('global'),[users,setUsers]=useState([]),[posts,setPosts]=useState([]),[stats,setStats]=useState({followers:0,following:0}),[pending,setPending]=useState([]),[following,setFollowing]=useState(new Set()),[friendStatus,setFriendStatus]=useState({}),[conversations,setConversations]=useState([]),[chat,setChat]=useState(null),[messages,setMessages]=useState([]),[text,setText]=useState(''),[search,setSearch]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const me=session?.user?.id;
 useEffect(()=>{supabase.auth.getSession().then(({data})=>setSession(data.session));const{data:l}=supabase.auth.onAuthStateChange((_e,s)=>setSession(s));return()=>l.subscription.unsubscribe()},[]);
 const load=async()=>{if(!me)return;setError('');try{const[g,f,s,p,c]=await Promise.all([getFeed(),getFriendsFeed(me),getFollowStats(me),getPendingFriendRequests(me),getMyConversations(me)]);setPosts(tab==='friends'?f:g);setStats(s);setPending(p);setConversations(c);const list=(await supabase.from('profiles').select('id,name,avatar_url,level,equipped_title').neq('id',me).order('name').limit(100)).data||[];setUsers(list);const ff=await getFollowing(me);setFollowing(new Set(ff.map(x=>x.id)));const fs={};for(const u of list){try{fs[u.id]=await getFriendRequestStatus(me,u.id)}catch{}}setFriendStatus(fs)}catch(e){setError(e.message||'Não foi possível carregar a área social.')}};
 useEffect(()=>{if(open&&me)load()},[open,me,tab]);
 useEffect(()=>{if(!chat)return;getMessages(chat.id).then(setMessages).catch(e=>setError(e.message));const ch=subscribeToMessages(chat.id,m=>setMessages(x=>x.some(v=>v.id===m.id)?x:[...x,m]));return()=>{supabase.removeChannel(ch)}},[chat]);
 const follow=async u=>{setBusy(true);try{if(following.has(u.id)){await unfollowUser(me,u.id);setFollowing(s=>{const n=new Set(s);n.delete(u.id);return n})}else{await followUser(me,u.id);setFollowing(s=>new Set([...s,u.id]))}setStats(await getFollowStats(me))}catch(e){setError(e.message)}finally{setBusy(false)}};
 const friend=async u=>{setBusy(true);try{const st=friendStatus[u.id];if(st?.status==='pending'&&st.sender_id===me)return;if(st?.status==='accepted')return;const r=await sendFriendRequest(me,u.id);setFriendStatus(s=>({...s,[u.id]:r}))}catch(e){setError(e.message)}finally{setBusy(false)}};
 const accept=async r=>{try{await respondFriendRequest(r.id,true);await load()}catch(e){setError(e.message)}};
 const openChat=async u=>{setBusy(true);try{const id=await createPrivateConversation(me,u.id);setChat({id,members:[u]})}catch(e){setError(e.message)}finally{setBusy(false)}};
 const send=async()=>{if(!chat||!text.trim())return;try{await sendMessage(chat.id,me,text);setText('')}catch(e){setError(e.message)}};
 if(!session)return null;
 return <>
  <button onClick={()=>setOpen(true)} style={{position:'fixed',right:16,bottom:82,zIndex:30,border:0,borderRadius:999,padding:'13px 16px',background:'#7A4356',color:'#fff',fontWeight:800,boxShadow:'0 8px 24px #0006'}}><Users size={18} style={{verticalAlign:'middle',marginRight:6}}/> Comunidade</button>
  {open&&<div style={{position:'fixed',inset:0,zIndex:100,background:'#140D12ee',display:'grid',placeItems:'center',padding:12}}><section style={{width:'min(100%,900px)',height:'min(92vh,760px)',background:'#1E1520',color:'#F5EFE6',border:'1px solid #7A4356',borderRadius:20,overflow:'hidden',display:'flex',flexDirection:'column'}}>
   <header style={{display:'flex',alignItems:'center',justifyContent:'space-between',padding:16,borderBottom:'1px solid #392633'}}><b style={{fontSize:20}}>🌐 Comunidade</b><button onClick={()=>{setOpen(false);setChat(null)}}><X/></button></header>
   <nav style={{display:'flex',gap:8,padding:10,overflowX:'auto'}}>{[['global','🌎 Global'],['friends','👥 Amigos'],['people','🔎 Jogadores'],['followers','👤 Seguidores'],['following','➡️ Seguindo'],['requests','🤝 Pedidos'],['chats','💬 Conversas']].map(([k,l])=><button key={k} onClick={()=>{setTab(k);setChat(null)}} style={{padding:'9px 12px',borderRadius:10,border:0,background:tab===k?'#C9A455':'#291C2B',color:tab===k?'#140D12':'#F5EFE6',fontWeight:800,whiteSpace:'nowrap'}}>{l}</button>)}</nav>
   <main style={{padding:16,overflow:'auto',flex:1}}>{error&&<div style={{background:'#4b2432',padding:10,borderRadius:10,marginBottom:10}}>{error}</div>}
    {tab==='global'||tab==='friends'?<div>{(posts||[]).map(p=><article key={p.id} style={{background:'#291C2B',padding:14,borderRadius:14,marginBottom:10}}><b>{p.profiles?.name||'Aventureiro'}</b><div style={{marginTop:8}}>{p.text}</div><small style={{color:'#A497A3'}}>{new Date(p.created_at).toLocaleString('pt-BR')}</small></article>)}{!posts.length&&<p style={{color:'#A497A3'}}>Nenhuma publicação encontrada.</p>}</div>:null}
    {tab==='people'&&<><div style={{display:'flex',gap:8,marginBottom:12}}><Search/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Procurar jogador..." style={{flex:1,padding:10,borderRadius:10}}/></div>{users.filter(u=>(u.name||'').toLowerCase().includes(search.toLowerCase())).map(u=>{const st=friendStatus[u.id];return <div key={u.id} style={{display:'flex',alignItems:'center',gap:10,background:'#291C2B',padding:12,borderRadius:12,marginBottom:8}}><div style={{flex:1}}><b>{u.name}</b><small style={{display:'block',color:'#A497A3'}}>Nível {u.level||1} · {u.equipped_title||'Aventureiro'}</small></div><button disabled={busy} onClick={()=>follow(u)}>{following.has(u.id)?<UserMinus size={18}/>:<UserPlus size={18}/>}</button>{st?.status==='accepted'?<button onClick={()=>openChat(u)}><MessageCircle size={18}/></button>:<button disabled={!!st||busy} onClick={()=>friend(u)}>{st?.status==='pending'?<UserCheck size={18}/>:<UserPlus size={18}/>}</button>}</div>})}</>}
    {(tab==='followers'||tab==='following')&&<div><div style={{display:'flex',gap:20,marginBottom:14}}><b>Seguidores: {stats.followers}</b><b>Seguindo: {stats.following}</b></div>{(tab==='followers'?[]:[]).map(()=>null)}<p style={{color:'#A497A3'}}>Use a aba Jogadores para seguir e gerenciar conexões.</p></div>}
    {tab==='requests'&&<div>{pending.map(r=><div key={r.id} style={{display:'flex',alignItems:'center',gap:10,background:'#291C2B',padding:12,borderRadius:12,marginBottom:8}}><b style={{flex:1}}>{r.profiles?.name||'Usuário'}</b><button onClick={()=>accept(r)}><UserCheck/> Aceitar</button><button onClick={async()=>{await respondFriendRequest(r.id,false);load()}}><UserMinus/> Recusar</button></div>)}{!pending.length&&<p>Nenhum pedido pendente.</p>}</div>}
    {tab==='chats'&&!chat&&<div>{conversations.map(c=>{const other=c.members.find(m=>m.id!==me);return <button key={c.id} onClick={()=>setChat(c)} style={{display:'block',width:'100%',textAlign:'left',background:'#291C2B',color:'#F5EFE6',border:0,padding:14,borderRadius:12,marginBottom:8}}><MessageCircle size={18}/> {other?.name||'Conversa'}</button>})}{!conversations.length&&<p>Nenhuma conversa. Faça amizade com alguém para iniciar.</p>}</div>}
    {chat&&<div style={{display:'flex',flexDirection:'column',height:'100%'}}><button onClick={()=>setChat(null)}>← Voltar</button><div style={{flex:1,overflow:'auto',padding:10}}>{messages.map(m=><div key={m.id} style={{textAlign:m.sender_id===me?'right':'left',margin:'8px 0'}}><span style={{display:'inline-block',padding:10,borderRadius:12,background:m.sender_id===me?'#7A4356':'#291C2B'}}>{m.text}</span></div>)}</div><div style={{display:'flex',gap:8}}><input value={text} onChange={e=>setText(e.target.value)} onKeyDown={e=>e.key==='Enter'&&send()} placeholder="Mensagem..." style={{flex:1,padding:12,borderRadius:10}}/><button onClick={send}><Send/></button></div></div>}
   </main>
  </section></div>}
 </>;
}
